# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c266a862367f6c873885ed9fb8af971e57b47128599a3ace2b8ddc607d577b9c1d00b3048e251f3e48d09924077760e820341dfb12ba69fb38e7e6e6e4b2215

test:
  secret_key_base: 7d4a326ea47ef38cb8f3c9c9586e364524cd7757430f9f0f6d1ce3da4399a1d56b520fa95293220a1c1eed35688ec1141c975966db82501b9a92c74806c7fb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
